name: Build Base Image

on:
  push:
    branches:
      - master
jobs:
  build1:
    name: ubuntu-latest
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
      - name: ll
        run: ll
      - name: tree
        run: tree /
      - name: pwd
        run: pwd