name: Build Base Image

on:
  push:
    branches:
      - master
jobs:
  build4:
    name: build4-latest
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
      - name: buildx
        run: docker buildx create --use --name mybuilder && docker buildx inspect mybuilder --bootstrap && docker buildx ls
  build5:
    name: build4-latest
    runs-on: 'macos-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
      - name: buildx
        run: docker buildx create --use --name mybuilder && docker buildx inspect mybuilder --bootstrap && docker buildx ls


