name: Build PHP Image

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build80:
    name: build-php-80
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        run: docker login --username tw2066 -p $DOCKERHUB_TOKEN

      - name: docker --version
        run: docker --version

      - name: docker buildx create
        run: docker buildx create --use --name mybuilder && docker buildx inspect mybuilder --bootstrap && docker buildx ls

      - name: docker buildx and push
        run: ./.github/workflows/build.sh 8.0 8.0 3.16 base
