name: Build Base Image

on:
  push:
    branches:
      - master
jobs:
  build1:
    name: ubuntu-latest
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
  build2:
    name: macos-latest
    runs-on: 'macos-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
  build3:
    name: macos-12
    runs-on: 'macos-12'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
