name: Build Base Image

on:
  push:
    branches:
      - master
jobs:
  build1:
    name: build1-latest
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
      - name: apt update
        run: sudo apt-get update
      - name: docker --version
        run: docker --version
      - name: buildx
        run: docker buildx create --use --name mybuilder && docker buildx inspect mybuilder --bootstrap && docker buildx ls

  build2:
    name: macos-latest
    runs-on: 'macos-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Uname
        run: uname -a
      - name: install
        run: brew install --cask docker && docker --version
      - name: buildx
        run: docker buildx create --use --name mybuilder && docker buildx inspect mybuilder --bootstrap && docker buildx ls


